import json
from datetime import date, datetime
from core.logging import get_logger
from analytics.factors.factor_engine import FactorEngine
from pathlib import Path
import pandas as pd

logger = get_logger(__name__)

class ReportGenerator:
    def __init__(self):
        self.live_dir = Path(__file__).resolve().parent.parent.parent / "research" / "live"
        self.reports_dir = self.live_dir / "reports"
        self.journal_dir = self.live_dir / "journal"
        self.portfolios_dir = self.live_dir / "portfolios"
        self.trades_dir = self.live_dir / "trades"
        
        self.reports_dir.mkdir(parents=True, exist_ok=True)
        self.journal_dir.mkdir(parents=True, exist_ok=True)
        
        self.engine = FactorEngine()
        
    def generate_monthly_report(self):
        target_date = date.today()
        logger.info(f"Generating Monthly Live Report for {target_date.strftime('%B %Y')}...")
        
        history_file = self.live_dir / "performance_history.json"
        hist = {}
        if history_file.exists():
            with open(history_file, "r", encoding="utf-8") as f:
                hist = json.load(f)
                
        snapshots = hist.get("daily_snapshots", [])
        
        port_return = "N/A"
        nifty_return = "N/A"
        excess_return = "N/A"
        
        if snapshots:
            start_val = hist.get("initial_capital", 1000000)
            end_val = snapshots[-1]["portfolio_value"]
            port_return_val = (end_val / start_val - 1) * 100
            port_return = f"{port_return_val:+.2f}%"
            
            start_nifty = hist.get("initial_nifty", 1)
            end_nifty = snapshots[-1].get("nifty_close", start_nifty)
            nifty_return_val = (end_nifty / start_nifty - 1) * 100 if start_nifty else 0
            nifty_return = f"{nifty_return_val:+.2f}%"
            
            excess_return = f"{(port_return_val - nifty_return_val):+.2f}%"
            
        ranks = self.engine.rank_universe(target_date, persist=False)
        top_stocks_str = "N/A"
        if not ranks.empty:
            top_stocks_str = ranks.head(10)[['rank', 'symbol', 'composite_score']].to_markdown(index=False)
            
        report_md = f"""# Atlas Monthly Report: {target_date.strftime('%B %Y')}

## Performance Summary
- **Portfolio Return:** {port_return}
- **NIFTY Return:** {nifty_return}
- **Excess Return (Alpha):** {excess_return}

## Current Top 10 Factor Rankings
The following assets possess the highest composite Factor scores for the upcoming month:

{top_stocks_str}

*Report autonomously generated by Atlas Live Engine.*
"""
        report_path = self.reports_dir / f"{target_date.strftime('%Y_%m')}_Report.md"
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(report_md)
            
        logger.info(f"Monthly Report generated at {report_path}")

    def generate_decision_journal(self):
        target_date = date.today()
        logger.info(f"Generating Decision Journal for {target_date.strftime('%B %Y')}...")
        
        # Load active portfolio
        active_port_file = self.portfolios_dir / "active_portfolio.json"
        portfolio = {}
        if active_port_file.exists():
            with open(active_port_file, "r", encoding="utf-8") as f:
                portfolio = json.load(f)
                
        weighting_scheme = portfolio.get("weighting_scheme", "Unknown")
        positions = portfolio.get("positions", [])
        
        # Load Trades to find removed stocks today
        ledger_file = self.trades_dir / "trade_ledger.json"
        removed_symbols = []
        if ledger_file.exists():
            with open(ledger_file, "r", encoding="utf-8") as f:
                ledger = json.load(f)
                today_str = target_date.isoformat()
                for t in ledger:
                    if t.get('action') == "SELL" and t.get('timestamp', '').startswith(today_str):
                        removed_symbols.append(t['symbol'])
        
        # Get factor rankings
        ranks = self.engine.rank_universe(target_date, persist=False)
        
        journal_md = f"# Atlas Decision Journal: {target_date.strftime('%B %Y')}\n\n"
        journal_md += f"**Rebalance Date:** {target_date}\n"
        journal_md += f"**Optimization Scheme:** {weighting_scheme}\n\n"
        
        journal_md += "## 1. Portfolio Additions & Allocations\n"
        journal_md += "The following stocks were included in the portfolio due to scoring in the top N of the Factor Composite engine. Allocations were determined by the weighting scheme.\n\n"
        
        journal_md += "| Symbol | Rank | Momentum Score | Volatility Score | Composite Score | Portfolio Weight | Reason for Inclusion |\n"
        journal_md += "|--------|------|----------------|------------------|-----------------|------------------|----------------------|\n"
        
        for pos in positions:
            sym = pos['symbol']
            weight = pos['weight'] * 100
            
            # Find rank details
            rank_row = ranks[ranks['symbol'] == sym] if not ranks.empty else pd.DataFrame()
            if not rank_row.empty:
                r_idx = rank_row['rank'].values[0]
                mom = rank_row['momentum_score'].values[0]
                vol = rank_row['volatility_score'].values[0]
                comp = rank_row['composite_score'].values[0]
            else:
                r_idx, mom, vol, comp = ("N/A", "N/A", "N/A", pos.get('factor_score', 'N/A'))
                
            reason = f"Ranked #{r_idx} by Factor Engine. Optimized weight via {weighting_scheme}."
            journal_md += f"| {sym} | {r_idx} | {mom:.2f} | {vol:.2f} | {comp:.2f} | {weight:.2f}% | {reason} |\n"
            
        journal_md += "\n## 2. Stocks Removed Since Last Rebalance\n"
        if removed_symbols:
            for rs in removed_symbols:
                journal_md += f"- **{rs}**: Dropped out of Top N factor rankings.\n"
        else:
            journal_md += "No stocks were removed in this rebalance cycle.\n"
            
        journal_md += "\n*Journal generated autonomously by Atlas Live Engine to guarantee full auditability of portfolio decisions.*\n"
        
        journal_path = self.journal_dir / f"Decision_Journal_{target_date.strftime('%Y_%m')}.md"
        with open(journal_path, "w", encoding="utf-8") as f:
            f.write(journal_md)
            
        logger.info(f"Decision Journal generated at {journal_path}")

if __name__ == "__main__":
    from core.logging import setup_logging
    setup_logging(log_level="INFO")
    rep = ReportGenerator()
    rep.generate_monthly_report()
    rep.generate_decision_journal()
