"""Add FactorRanking and ema_200

Revision ID: 03f05a2fa169
Revises: efc5ead25ce9
Create Date: 2026-06-22 07:46:05.879825+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03f05a2fa169'
down_revision: Union[str, None] = 'efc5ead25ce9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('factor_rankings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('run_id', sa.String(length=50), nullable=False),
    sa.Column('ranking_date', sa.Date(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('top_n', sa.Integer(), nullable=True),
    sa.Column('momentum_raw', sa.Float(), nullable=True),
    sa.Column('trend_raw', sa.Float(), nullable=True),
    sa.Column('rs_raw', sa.Float(), nullable=True),
    sa.Column('volatility_raw', sa.Float(), nullable=True),
    sa.Column('liquidity_raw', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('trend_score', sa.Float(), nullable=True),
    sa.Column('rs_score', sa.Float(), nullable=True),
    sa.Column('volatility_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ranking_date', 'symbol', name='uq_factor_ranking_date_symbol')
    )
    op.create_index(op.f('ix_factor_rankings_ranking_date'), 'factor_rankings', ['ranking_date'], unique=False)
    op.create_index(op.f('ix_factor_rankings_run_id'), 'factor_rankings', ['run_id'], unique=False)
    op.create_index(op.f('ix_factor_rankings_symbol'), 'factor_rankings', ['symbol'], unique=False)
    op.add_column('market_indicators', sa.Column('ema_200', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('market_indicators', 'ema_200')
    op.drop_index(op.f('ix_factor_rankings_symbol'), table_name='factor_rankings')
    op.drop_index(op.f('ix_factor_rankings_run_id'), table_name='factor_rankings')
    op.drop_index(op.f('ix_factor_rankings_ranking_date'), table_name='factor_rankings')
    op.drop_table('factor_rankings')
    # ### end Alembic commands ###
