"""Add market data cache tables

Revision ID: efc5ead25ce9
Revises: 0001
Create Date: 2026-06-19 18:08:21.664420+00:00

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efc5ead25ce9'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_indicators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('ema_20', sa.Float(), nullable=True),
    sa.Column('ema_50', sa.Float(), nullable=True),
    sa.Column('sma_20', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('macd', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('atr_14', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_indicators_symbol_date')
    )
    op.create_index(op.f('ix_market_indicators_date'), 'market_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_market_indicators_symbol'), 'market_indicators', ['symbol'], unique=False)
    op.create_table('symbol_metadata',
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('last_synced', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('first_date', sa.Date(), nullable=True),
    sa.Column('last_date', sa.Date(), nullable=True),
    sa.Column('total_candles', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('symbol')
    )
    op.drop_index(op.f('ix_stocks_is_active'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_system_logs_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_ts'), table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_table('market_data')

    op.create_table('market_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('adj_close', sa.Float(), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_market_data_symbol_date')
    )
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_data', sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('market_data', sa.Column('timeframe', sa.VARCHAR(length=5), server_default=sa.text("'1d'::character varying"), autoincrement=False, nullable=False))
    op.drop_constraint('uq_market_data_symbol_date', 'market_data', type_='unique')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.create_unique_constraint(op.f('uq_market_data_symbol_tf_ts'), 'market_data', ['symbol', 'timeframe', 'ts'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_market_data_ts'), 'market_data', ['ts'], unique=False)
    op.create_index(op.f('ix_market_data_symbol_ts'), 'market_data', ['symbol', 'ts'], unique=False)
    op.alter_column('market_data', 'close',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('market_data', 'low',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('market_data', 'high',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('market_data', 'open',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=4),
               existing_nullable=False)
    op.alter_column('market_data', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('market_data', 'adj_close')
    op.drop_column('market_data', 'date')
    op.create_table('system_logs',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('level', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('logger', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('system_logs_pkey'))
    )
    op.create_index(op.f('ix_system_logs_ts'), 'system_logs', ['ts'], unique=False)
    op.create_index(op.f('ix_system_logs_level'), 'system_logs', ['level'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sector', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(length=10), server_default=sa.text("'NSE'::character varying"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('stocks_pkey')),
    sa.UniqueConstraint('symbol', name=op.f('stocks_symbol_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=False)
    op.create_index(op.f('ix_stocks_is_active'), 'stocks', ['is_active'], unique=False)
    op.drop_table('symbol_metadata')
    op.drop_index(op.f('ix_market_indicators_symbol'), table_name='market_indicators')
    op.drop_index(op.f('ix_market_indicators_date'), table_name='market_indicators')
    op.drop_table('market_indicators')
    # ### end Alembic commands ###
